import dotenv from "dotenv";
dotenv.config();

export default {
  SERVER_PORT: process.env.PORT,
  DATABASE_HOST: process.env.DATABASE_HOST,
  DATABASE_USER: process.env.DATABASE_NAME,
  DATABASE_PASSWORD: process.env.DATABASE_PASSWORD,
  DATABASE_NAME: process.env.DATABASE_NAME,
  DATABASE_PORT: process.env.DATABASE_PORT,
  CLOUDINARY_CLOUD_NAME: process.env.CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY: process.env.CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET: process.env.CLOUDINARY_API_SECRET,
  TOKEN_KEY: process.env.TOKEN_KEY,
  SMTP_AUTH_TYPE: process.env.SMTP_AUTH_TYPE,
  SMTP_AUTH_EMAIL: process.env.SMTP_AUTH_EMAIL,
  SMTP_AUTH_PASSWORD: process.env.SMTP_AUTH_PASSWORD
};
